//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICSLicenseMaintV2 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LicenseMaintStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LicenseMaintStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICSLicenseMaintV2.LicenseMaintStrings", typeof(LicenseMaintStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed.
        /// </summary>
        public static string ChangeTime {
            get {
                return ResourceManager.GetString("ChangeTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed Type.
        /// </summary>
        public static string ChangeType {
            get {
                return ResourceManager.GetString("ChangeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Changed By.
        /// </summary>
        public static string ChangeUserID {
            get {
                return ResourceManager.GetString("ChangeUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Issued.
        /// </summary>
        public static string DateIssued {
            get {
                return ResourceManager.GetString("DateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Remaining.
        /// </summary>
        public static string DaysRemaining {
            get {
                return ResourceManager.GetString("DaysRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of days to add to add (from today) to the expiration date for the license..
        /// </summary>
        public static string HelpAddDays {
            get {
                return ResourceManager.GetString("HelpAddDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The customer to which the license belongs..
        /// </summary>
        public static string HelpCustomer {
            get {
                return ResourceManager.GetString("HelpCustomer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date that the license record was created..
        /// </summary>
        public static string HelpDateIssued {
            get {
                return ResourceManager.GetString("HelpDateIssued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date that the license record will expire (Expired records will be highlighted in red)..
        /// </summary>
        public static string HelpExpiryDate {
            get {
                return ResourceManager.GetString("HelpExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation directory on the customer&apos;s machine..
        /// </summary>
        public static string HelpInstallPath {
            get {
                return ResourceManager.GetString("HelpInstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date/time of the most recent change to the licensing record made by someone at ICS..
        /// </summary>
        public static string HelpLastChanged {
            get {
                return ResourceManager.GetString("HelpLastChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License ID which can be found in either the weblicense or RFSV3 license files (depending on the version) in the RTTC\License directory..
        /// </summary>
        public static string HelpLicenseID {
            get {
                return ResourceManager.GetString("HelpLicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A hash of various machine values.
        ///If this changes for the same server it means a customer has made a change to one of the values on their server and you will need to setup a new license..
        /// </summary>
        public static string HelpMachineID {
            get {
                return ResourceManager.GetString("HelpMachineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server name of the licensed machine..
        /// </summary>
        public static string HelpMachineName {
            get {
                return ResourceManager.GetString("HelpMachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If check this license does not expire. If not checked this license will expire on the &quot;Expires&quot; date..
        /// </summary>
        public static string HelpPermanent {
            get {
                return ResourceManager.GetString("HelpPermanent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of RF-SMART users.
        ///This should match the sum of all of the &quot;RF-SMART for &lt;ERP&gt; User&quot; records on the customer record in NetSuite..
        /// </summary>
        public static string HelpUserCount {
            get {
                return ResourceManager.GetString("HelpUserCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install Path.
        /// </summary>
        public static string InstallPath {
            get {
                return ResourceManager.GetString("InstallPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Requested Update.
        /// </summary>
        public static string LastRequestedUpdate {
            get {
                return ResourceManager.GetString("LastRequestedUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to License ID.
        /// </summary>
        public static string LicenseID {
            get {
                return ResourceManager.GetString("LicenseID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine ID.
        /// </summary>
        public static string MachineID {
            get {
                return ResourceManager.GetString("MachineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Machine Name.
        /// </summary>
        public static string MachineName {
            get {
                return ResourceManager.GetString("MachineName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time Out.
        /// </summary>
        public static string TimeOut {
            get {
                return ResourceManager.GetString("TimeOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Count.
        /// </summary>
        public static string UserCount {
            get {
                return ResourceManager.GetString("UserCount", resourceCulture);
            }
        }
    }
}
