//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ICSLicenseMaintV2.ICSLicensing {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="RFSLicenseSoap", Namespace="http://icsfl.com/")]
    public partial class RFSLicense : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetNewLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetUpdatedLicenseOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetNewLicFromCrypKeyDataOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public RFSLicense() {
            this.Url = global::ICSLicenseMaintV2.Properties.Settings.Default.ICSLicenseMaintV2_ICSLicensing_RFSLicense;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetNewLicenseCompletedEventHandler GetNewLicenseCompleted;
        
        /// <remarks/>
        public event GetUpdatedLicenseCompletedEventHandler GetUpdatedLicenseCompleted;
        
        /// <remarks/>
        public event GetNewLicFromCrypKeyDataCompletedEventHandler GetNewLicFromCrypKeyDataCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icsfl.com/GetNewLicense", RequestNamespace="http://icsfl.com/", ResponseNamespace="http://icsfl.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetNewLicense(string RequestData, out string ResponseData, out string ErrorMessage) {
            object[] results = this.Invoke("GetNewLicense", new object[] {
                        RequestData});
            ResponseData = ((string)(results[1]));
            ErrorMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewLicenseAsync(string RequestData) {
            this.GetNewLicenseAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void GetNewLicenseAsync(string RequestData, object userState) {
            if ((this.GetNewLicenseOperationCompleted == null)) {
                this.GetNewLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewLicenseOperationCompleted);
            }
            this.InvokeAsync("GetNewLicense", new object[] {
                        RequestData}, this.GetNewLicenseOperationCompleted, userState);
        }
        
        private void OnGetNewLicenseOperationCompleted(object arg) {
            if ((this.GetNewLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewLicenseCompleted(this, new GetNewLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icsfl.com/GetUpdatedLicense", RequestNamespace="http://icsfl.com/", ResponseNamespace="http://icsfl.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetUpdatedLicense(string RequestData, out string ResponseData, out string ErrorMessage) {
            object[] results = this.Invoke("GetUpdatedLicense", new object[] {
                        RequestData});
            ResponseData = ((string)(results[1]));
            ErrorMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetUpdatedLicenseAsync(string RequestData) {
            this.GetUpdatedLicenseAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void GetUpdatedLicenseAsync(string RequestData, object userState) {
            if ((this.GetUpdatedLicenseOperationCompleted == null)) {
                this.GetUpdatedLicenseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetUpdatedLicenseOperationCompleted);
            }
            this.InvokeAsync("GetUpdatedLicense", new object[] {
                        RequestData}, this.GetUpdatedLicenseOperationCompleted, userState);
        }
        
        private void OnGetUpdatedLicenseOperationCompleted(object arg) {
            if ((this.GetUpdatedLicenseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetUpdatedLicenseCompleted(this, new GetUpdatedLicenseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://icsfl.com/GetNewLicFromCrypKeyData", RequestNamespace="http://icsfl.com/", ResponseNamespace="http://icsfl.com/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public bool GetNewLicFromCrypKeyData(string RequestData, out string ResponseData, out string ErrorMessage) {
            object[] results = this.Invoke("GetNewLicFromCrypKeyData", new object[] {
                        RequestData});
            ResponseData = ((string)(results[1]));
            ErrorMessage = ((string)(results[2]));
            return ((bool)(results[0]));
        }
        
        /// <remarks/>
        public void GetNewLicFromCrypKeyDataAsync(string RequestData) {
            this.GetNewLicFromCrypKeyDataAsync(RequestData, null);
        }
        
        /// <remarks/>
        public void GetNewLicFromCrypKeyDataAsync(string RequestData, object userState) {
            if ((this.GetNewLicFromCrypKeyDataOperationCompleted == null)) {
                this.GetNewLicFromCrypKeyDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetNewLicFromCrypKeyDataOperationCompleted);
            }
            this.InvokeAsync("GetNewLicFromCrypKeyData", new object[] {
                        RequestData}, this.GetNewLicFromCrypKeyDataOperationCompleted, userState);
        }
        
        private void OnGetNewLicFromCrypKeyDataOperationCompleted(object arg) {
            if ((this.GetNewLicFromCrypKeyDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetNewLicFromCrypKeyDataCompleted(this, new GetNewLicFromCrypKeyDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetNewLicenseCompletedEventHandler(object sender, GetNewLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ResponseData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetUpdatedLicenseCompletedEventHandler(object sender, GetUpdatedLicenseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetUpdatedLicenseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetUpdatedLicenseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ResponseData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    public delegate void GetNewLicFromCrypKeyDataCompletedEventHandler(object sender, GetNewLicFromCrypKeyDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.6.81.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetNewLicFromCrypKeyDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetNewLicFromCrypKeyDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string ResponseData {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
        
        /// <remarks/>
        public string ErrorMessage {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[2]));
            }
        }
    }
}

#pragma warning restore 1591